### ISSUE TITLE
Clickhouse image is missing tzdata

### ISSUE THREAD

**Issue by ezhevita** [Sentry-ARM/self-hosted#1]
### Version

21.9.0.dev0

### Steps to Reproduce

1. Run it
2. Trying to get projects will result in a error because there is no timezone available for clickhouse

### Expected Result

No error

### Actual Result

Error

**Comment by huoyunhao** [comment]
me to  +1

**Comment by Xxs-7** [comment]
Had this problem been solved? It still remains in the newest release.
when I run 'test.sh', the logs show:
> ▶ Running moar tests !!!
Creating test event...
An error occurred, caught SIGERR on line 96
Cleaning up...
Done.

**Comment by ezhevita** [comment]
> Had this problem been solved?

No, but there is a workaround - `docker exec` into container and install tzdata manually
